/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Recipe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecipeRequest"];
                    "text/json": components["schemas"]["RecipeRequest"];
                    "application/*+json": components["schemas"]["RecipeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RecipeResponse"];
                        "application/json": components["schemas"]["RecipeResponse"];
                        "text/json": components["schemas"]["RecipeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecipeRequest: {
            prompt: string;
            /** Format: int32 */
            servings?: number | string;
        };
        RecipeResponse: {
            titel?: string;
            ingredienser?: string[];
            instruktioner?: string[];
            /** Format: double */
            tillagningstid?: number | string;
            /** Format: int32 */
            portioner?: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
